import { type Task } from "../types/Task";

export const TASK_STATUSES = ["pending", "in-progress", "completed"] as const;

export const SAMPLE_TASKS: Task[] = [
  {
    id: "1",
    title: "Review PR #123",
    description: "Need to review the authentication changes before merging",
    status: "in-progress",
    createdAt: new Date(2024, 6, 31),
    updatedAt: new Date(2024, 6, 31),
  },
  {
    id: "2",
    title: "Update documentation",
    description: "Add examples for the new API endpoints",
    status: "in-progress",
    createdAt: new Date(2024, 6, 30),
    updatedAt: new Date(2024, 6, 30),
  },
  {
    id: "3",
    title: "Fix login bug",
    description: "Users can't login with special characters in password",
    status: "pending",
    createdAt: new Date(2024, 6, 29),
    updatedAt: new Date(2024, 6, 29),
  },
  {
    id: "4",
    title: "Setup CI/CD pipeline",
    description: "Configure automated testing and deployment",
    status: "pending",
    createdAt: new Date(2024, 6, 28),
    updatedAt: new Date(2024, 6, 28),
  },
  {
    id: "5",
    title: "Database migration",
    description: "Migrate user table to new schema",
    status: "completed",
    createdAt: new Date(2024, 6, 27),
    updatedAt: new Date(2024, 6, 27),
  },
  {
    id: "6",
    title: "Design new dashboard",
    description: "Create wireframes and mockups for the admin dashboard",
    status: "pending",
    createdAt: new Date(2024, 6, 26),
    updatedAt: new Date(2024, 6, 26),
  },
  {
    id: "7",
    title: "Implement user authentication",
    description: "Add JWT token-based authentication system",
    status: "in-progress",
    createdAt: new Date(2024, 6, 25),
    updatedAt: new Date(2024, 6, 25),
  },
  {
    id: "8",
    title: "Write unit tests",
    description: "Add comprehensive test coverage for core modules",
    status: "pending",
    createdAt: new Date(2024, 6, 24),
    updatedAt: new Date(2024, 6, 24),
  },
  {
    id: "9",
    title: "Optimize database queries",
    description: "Improve performance of slow-running database operations",
    status: "completed",
    createdAt: new Date(2024, 6, 23),
    updatedAt: new Date(2024, 6, 23),
  },
  {
    id: "10",
    title: "Deploy to production",
    description: "Set up production environment and deploy latest version",
    status: "completed",
    createdAt: new Date(2024, 6, 22),
    updatedAt: new Date(2024, 6, 22),
  },
  {
    id: "11",
    title: "Code review session",
    description: "Conduct team code review for recent changes",
    status: "pending",
    createdAt: new Date(2024, 6, 21),
    updatedAt: new Date(2024, 6, 21),
  },
  {
    id: "12",
    title: "Update dependencies",
    description: "Upgrade packages to latest versions and fix breaking changes",
    status: "in-progress",
    createdAt: new Date(2024, 6, 20),
    updatedAt: new Date(2024, 6, 20),
  },
];
